const PRODUCTS = [

  // ─────────────────────────────────────────────────────────────
  // HOME STANDBY  (20 products · 15–30 kW · $2,500–$4,000)
  // ─────────────────────────────────────────────────────────────

  {
    id: "yanmar-15kw-home-001",
    name: "Yanmar YDG15NH Home Standby",
    brand: "Yanmar",
    category: "home-standby",
    kw: 15,
    fuel: "Natural Gas / Propane",
    price: 2500,
    originalPrice: 2950,
    description: "The Yanmar YDG15NH delivers reliable 15kW standby power with whisper-quiet operation and automatic transfer for seamless whole-home backup.",
    features: ["Automatic transfer switch included", "EPA-compliant natural gas engine", "Weather-resistant aluminium enclosure", "Wi-Fi remote monitoring"],
    inStock: true,
    badge: null,
    image: "https://wholesale-generators.com/wp-content/uploads/2025/09/15kW-Yanmar.jpg",
    imageSearch: "Yanmar home standby generator 15kw natural gas"
  },
  {
    id: "generac-18kw-home-002",
    name: "Generac Guardian 18kW Home Standby",
    brand: "Generac",
    category: "home-standby",
    kw: 18,
    fuel: "Natural Gas / Propane",
    price: 2850,
    originalPrice: 3300,
    description: "The Generac Guardian 18kW delivers whole-home backup power with automatic operation. Runs on natural gas or LP and starts within seconds of an outage.",
    features: ["Automatic 10-second transfer", "True Power Technology for clean electricity", "Wi-Fi Mobile Link monitoring", "All-weather aluminium enclosure"],
    inStock: true,
    badge: null,
    image: "https://th.bing.com/th/id/R.946294a47dd91f52a1ff54fe9d6afab7?rik=C8Z7ppwoyeoUbA&pid=ImgRaw&r=0",
    imageSearch: "Generac Guardian 18kW home standby generator"
  },
  {
    id: "yanmar-20kw-25kva-home-003",
    name: "Yanmar YDG20NH Home Standby",
    brand: "Yanmar",
    category: "home-standby",
    kw: 20,
    fuel: "Natural Gas / Propane",
    price: 2900,
    originalPrice: 3400,
    description: "The YDG20NH powers your entire home including HVAC, appliances, and lighting. Yanmar's industrial-grade reliability in a residential package.",
    features: ["Whole-home backup capability", "Auto-voltage regulation", "Maintenance alert system", "5-year powertrain warranty"],
    inStock: true,
    badge: null,
    image: "https://image.made-in-china.com/2f0j00DVEcmAdBGHkn/20kw-25kVA-Super-Silent-Yanmar-Diesel-Generator-Set.jpg",
    imageSearch: "Yanmar home standby generator 20kw"
  },
  {
    id: "yanmar-20kw-home-004",
    name: "Yanmar YDG20PH Propane Standby",
    brand: "Yanmar",
    category: "home-standby",
    kw: 20,
    fuel: "Propane",
    price: 2950,
    originalPrice: 3450,
    description: "Propane-dedicated 20kW standby generator — ideal for rural homes without natural gas infrastructure. Connects directly to your LP tank.",
    features: ["Dedicated propane engine tuning", "Integrated load management", "Compact footprint — 48\" x 25\"", "Cold-weather starting package"],
    inStock: true,
    badge: null,
    image: "https://img.lazcdn.com/g/ff/kf/S975aa53945cd46f18a7f729f285a8637A.jpg_720x720q80.jpg",
    imageSearch: "Yanmar propane standby generator 20kw"
  },
  {
    id: "yanmar-22kva-home-005",
    name: "Yanmar YDG22NH Home Standby",
    brand: "Yanmar",
    category: "home-standby",
    kw: 22,
    fuel: "Natural Gas / Propane",
    price: 3100,
    originalPrice: 3600,
    description: "22kW standby power with Yanmar's advanced load-sensing technology. Handles large homes, workshops, and EV charging simultaneously.",
    features: ["Load-sensing voltage regulation", "NEMA 3R weatherproof enclosure", "Dual-fuel (NG or LP) capability", "Remote monitoring app included"],
    inStock: true,
    badge: null,
    image: "https://allgenerators.com.au/wp-content/uploads/2023/05/22-kv6.jpg",
    imageSearch: "Yanmar standby generator 22kva"
  },
  {
    id: "yanmar-25kw-home-006",
    name: "Yanmar YDG25PH Home Standby",
    brand: "Yanmar",
    category: "home-standby",
    kw: 25,
    fuel: "Propane",
    price: 3300,
    originalPrice: 3850,
    description: "The YDG25PH is engineered for large estate homes and light commercial properties requiring 25kW of reliable propane standby power.",
    features: ["1800 RPM slow-speed engine", "Ultra-low THD for sensitive equipment", "Stainless steel exhaust system", "Extended 500-hour oil change intervals"],
    inStock: true,
    badge: null,
    image: "https://assets.northerntool.com/cdn-cgi/image/fit=scale-down,width=%7Bwidth%7D/products/167/images/167192.jpg",
    imageSearch: "Yanmar propane generator 25kw standby"
  },
  {
    id: "yanmar-28kw-home-007",
    name: "Yanmar YDG28PH Home Standby",
    brand: "Yanmar",
    category: "home-standby",
    kw: 28,
    fuel: "Propane",
    price: 3600,
    originalPrice: 4100,
    description: "28kW of propane standby power with premium enclosure and 7-year structural warranty. One of the most powerful residential units Yanmar offers.",
    features: ["Whole-home 200A transfer switch", "Smart load prioritisation", "Galvanised steel base rail", "Annual service reminder system"],
    inStock: true,
    badge: "New",
    image: "https://static.wixstatic.com/media/d7872e_cfe433d292e041dda2736e700f36ba3b~mv2.jpg/v1/fill/w_900,h_544,al_c,lg_1,q_85/d7872e_cfe433d292e041dda2736e700f36ba3b~mv2.jpg",
    imageSearch: "Yanmar propane generator 28kw"
  },
  {
    id: "yanmar-30kw-home-008",
    name: "Yanmar YDG30NH Home Standby",
    brand: "Yanmar",
    category: "home-standby",
    kw: 30,
    fuel: "Natural Gas / Propane",
    price: 3900,
    originalPrice: 4500,
    description: "Yanmar's flagship 30kW residential standby generator. Powers everything — HVAC, pool pumps, EV charger, and full household load simultaneously.",
    features: ["Dual-fuel NG/LP with auto-switchover", "Premium powder-coat steel enclosure", "Integrated utility relay", "Wi-Fi + cellular remote monitoring"],
    inStock: true,
    badge: "New",
    image: "https://image.made-in-china.com/2f0j00VzOqkIaPbJul/Original-Factory-Supply-30kw-37-5kVA-Automatic-Pure-Copper-Diesel-Generator-Set.jpg",
    imageSearch: "Yanmar 30kw home standby generator"
  },

  {
    id: "generac-18kw-home-009",
    name: "Generac Guardian 18kW",
    brand: "Generac",
    category: "home-standby",
    kw: 18,
    fuel: "Natural Gas / Propane",
    price: 2799,
    originalPrice: 3199,
    description: "America's #1 selling home standby generator. The Guardian 18kW starts automatically and powers your home within seconds of an outage.",
    features: ["Wi-Fi enabled Mobile Link monitoring", "True Power Technology for clean power", "All-weather steel enclosure", "Free 5-year warranty with activation"],
    inStock: true,
    badge: "Best Seller",
    image: "https://www.genlitecpower.com/Uploads/pro/18kva-Yanmar-Diesel-Generator-EU-Stage-V.408.3-3.jpg",
    imageSearch: "Generac Guardian 18kW home standby generator"
  },
  {
    id: "generac-22kw-home-010",
    name: "Generac Guardian 22kW",
    brand: "Generac",
    category: "home-standby",
    kw: 22,
    fuel: "Natural Gas / Propane",
    price: 3199,
    originalPrice: 3699,
    description: "The best-selling 22kW home backup generator in the US. Powers central AC, appliances, and electronics without interruption.",
    features: ["Automatic whole-home transfer", "Quietest generator in its class", "7-year limited warranty", "Works with Generac PWRview energy monitor"],
    inStock: true,
    badge: "Best Seller",
    image: "https://tse4.mm.bing.net/th/id/OIP._1lGhFoGOu15zEP_V0t7eQHaFR?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Generac Guardian 22kW home standby"
  },
  {
    id: "generac-24kw-home-011",
    name: "Generac Guardian 24kW",
    brand: "Generac",
    category: "home-standby",
    kw: 24,
    fuel: "Natural Gas / Propane",
    price: 3499,
    originalPrice: 3999,
    description: "24kW Guardian Series with whole-house switch — covers large homes up to 5,000 sq ft. Runs on existing natural gas or LP supply.",
    features: ["200A whole-house transfer switch", "Runs on natural gas or LP propane", "LED status display panel", "Free Mobile Link subscription"],
    inStock: true,
    badge: null,
    image: "https://www.generac.com/globalassets/products/residential/standby-generators/gaseous/g0072090--24kw/7209-pdp-images-1.jpg",
    imageSearch: "Generac Guardian 24kW generator"
  },
  {
    id: "generac-26kw-home-012",
    name: "Generac Guardian 26kW",
    brand: "Generac",
    category: "home-standby",
    kw: 26,
    fuel: "Natural Gas / Propane",
    price: 3799,
    originalPrice: 4299,
    description: "Generac's most powerful air-cooled home standby. The 26kW Guardian handles the largest residential loads with ease.",
    features: ["Largest air-cooled home standby available", "Wi-Fi with auto-firmware updates", "Includes whole-house 200A switch", "Carbon monoxide safety shutoff"],
    inStock: true,
    badge: null,
    image: "https://www.acmetools.com/dw/image/v2/BHBS_PRD/on/demandware.static/-/Sites-acme-catalog-m-en/default/dw1de0f1db/images/images/catalog/product/696471087314/generac-guardian-26kw-air-cooled-standby-generator-with-whole-house-switch-wi-fi-enabled-7291-detail-view-8.jpg",
    imageSearch: "Generac Guardian 26kW generator"
  },

  {
    id: "kohler-20kw-home-013",
    name: "Kohler 20RESCL 20kW Standby",
    brand: "Kohler",
    category: "home-standby",
    kw: 20,
    fuel: "Natural Gas / Propane",
    price: 3099,
    originalPrice: 3599,
    description: "Kohler's OnCue Plus-enabled 20kW standby features premium sound attenuation and legendary Kohler durability for reliable whole-home backup.",
    features: ["OnCue Plus remote monitoring", "Sound-attenuated enclosure", "Fast-response transfer under 10 sec", "Corrosion-proof composite housing"],
    inStock: true,
    badge: "Best Seller",
    image: "https://tse2.mm.bing.net/th/id/OIP.nJOVdtIF-tPRNPFC-IWW-QHaEe?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Kohler 20kW home standby generator"
  },
  {
    id: "kohler-24kw-home-014",
    name: "Kohler 24RCL 24kW Standby",
    brand: "Kohler",
    category: "home-standby",
    kw: 24,
    fuel: "Natural Gas / Propane",
    price: 3499,
    originalPrice: 3999,
    description: "The Kohler 24RCL powers large homes and light commercial buildings with 24kW of clean, consistent standby power and premium remote monitoring.",
    features: ["Advanced power management module", "Bluetooth + Wi-Fi connectivity", "Galvanised steel enclosure", "5-year comprehensive warranty"],
    inStock: true,
    badge: null,
    image: "https://cdn11.bigcommerce.com/s-fc9pilzlet/images/stencil/1280x1280/products/7245/18820/85522b91-a989-4108-8fed-e340a8ffa7ed_kohler24kwgenerator24rclarightfront2000x1334__20806.1749825843.jpg?c=1",
    imageSearch: "Kohler 24kW standby generator"
  },
  {
    id: "kohler-30kw-home-015",
    name: "Kohler 30RCL 30kW Standby",
    brand: "Kohler",
    category: "home-standby",
    kw: 30,
    fuel: "Natural Gas / Propane",
    price: 3999,
    originalPrice: 4599,
    description: "Kohler's 30kW flagship residential standby — the only choice for estate homes, farms, and properties with high continuous load requirements.",
    features: ["Rated for continuous standby operation", "Ultra-quiet 63 dB noise level", "Aluminium housing — rust-proof for life", "Priority load controller included"],
    inStock: true,
    badge: null,
    image: "https://bnhgenerators.com/wp-content/uploads/2022/03/24_30RCL_3.jpg",
    imageSearch: "Kohler 30kW standby generator residential"
  },

  {
    id: "cummins-20kw-home-016",
    name: "Cummins RS20A 20kW Standby",
    brand: "Cummins",
    category: "home-standby",
    kw: 20,
    fuel: "Natural Gas / Propane",
    price: 2999,
    originalPrice: 3499,
    description: "Cummins QuietConnect 20kW — one of the quietest home standby generators in the industry at just 63 dB, backed by Cummins' global service network.",
    features: ["QuietConnect sound barrier technology", "63 dB ultra-low noise", "Cummins 5-year/2,000-hour warranty", "Corrosion-resistant fibreglass panel"],
    inStock: true,
    badge: null,
    image: "https://bnhgenerators.com/wp-content/uploads/2022/03/A061C591_1.jpg",
    imageSearch: "Cummins QuietConnect 20kW home standby generator"
  },
  {
    id: "cummins-22kw-home-017",
    name: "Cummins RS22A 22kW Standby",
    brand: "Cummins",
    category: "home-standby",
    kw: 22,
    fuel: "Natural Gas / Propane",
    price: 3299,
    originalPrice: 3799,
    description: "The RS22A combines Cummins engine quality with whisper-quiet operation. Suitable for homes up to 4,000 sq ft with full HVAC and appliance load.",
    features: ["Onan engine — proven in millions of RVs", "Automatic voltage regulation", "LED diagnostic display", "Single-hand oil drain service port"],
    inStock: true,
    badge: null,
    image: "https://th.bing.com/th/id/R.43fa780f136766749653fc81b35ceb65?rik=4QzulahzvimNEw&pid=ImgRaw&r=0",
    imageSearch: "Cummins RS22A home standby generator"
  },
  {
    id: "cummins-30kw-home-018",
    name: "Cummins RS30A 30kW Standby",
    brand: "Cummins",
    category: "home-standby",
    kw: 30,
    fuel: "Natural Gas / Propane",
    price: 3899,
    originalPrice: 4399,
    description: "30kW of Cummins reliability for the most demanding residential standby applications. Includes a 200A whole-house transfer switch and 5-year warranty.",
    features: ["200A whole-house transfer switch", "Mobile app remote monitoring", "5-year / 2,000-hour warranty", "Snap-on modular service panels"],
    inStock: true,
    badge: null,
    image: "https://tse4.mm.bing.net/th/id/OIP.aJiAIMzpv9xOiaByLaRPvAHaEU?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Cummins 30kW standby generator residential"
  },

  {
    id: "johndeere-30kw-home-019",
    name: "John Deere 30kW Standby",
    brand: "John Deere",
    category: "home-standby",
    kw: 30,
    fuel: "Natural Gas",
    price: 2599,
    originalPrice: 2999,
    description: "John Deere builds generators with the same legendary toughness as their agricultural equipment. The 30kW standby protects your home year-round.",
    features: ["John Deere PowerTech engine", "Powder-coat steel enclosure", "Automatic exercise cycle", "US-based dealer service network"],
    inStock: true,
    badge: null,
    image: "https://i.ebayimg.com/images/g/TLoAAeSw5jFprie-/s-l1600.webp",
    imageSearch: "John Deere 30kW home standby generator"
  },
  {
    id: "johndeere-20kw-home-020",
    name: "John Deere 20kW Diesel Standby",
    brand: "John Deere",
    category: "home-standby",
    kw: 20,
    fuel: "Natural Gas",
    price: 2999,
    originalPrice: 3499,
    description: "The John Deere 20kW delivers agricultural-grade reliability in a residential standby package. Automatic transfer, auto-exercise, and remote diagnostics included.",
    features: ["Green-label PowerTech NG engine", "Auto-exercise weekly scheduler", "Weatherproof NEMA 3R cabinet", "Dealer-supported service across all 50 states"],
    inStock: true,
    badge: null,
    image: "https://tse1.mm.bing.net/th/id/OIP.mSdhpeRe-GijhBgFPxCuxwHaGI?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "John Deere 20kW home standby generator"
  },


  // ─────────────────────────────────────────────────────────────
  // COMMERCIAL  (20 products · 20–100 kW · $2,500–$4,000)
  // ─────────────────────────────────────────────────────────────

  {
    id: "yanmar-20kw-comm-021",
    name: "Yanmar YDG20DC Commercial",
    brand: "Yanmar",
    category: "commercial",
    kw: 20,
    fuel: "Diesel",
    price: 2500,
    originalPrice: 2950,
    description: "Entry-level commercial diesel generator from Yanmar. Ideal for small businesses, offices, and retail facilities requiring reliable standby power.",
    features: ["Tier-4 Final EPA compliant diesel", "Skid-mounted for easy relocation", "Digital control panel with fault logging", "Paralleling-ready output terminals"],
    inStock: true,
    badge: null,
    image: "https://tse1.mm.bing.net/th/id/OIP.rPArzWoVCIAuF893KGXxSAHaE5?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Yanmar 20kW commercial diesel generator"
  },
  {
    id: "yanmar-30kw-comm-022",
    name: "Yanmar YDG30DC Commercial",
    brand: "Yanmar",
    category: "commercial",
    kw: 30,
    fuel: "Diesel",
    price: 2800,
    originalPrice: 3300,
    description: "The YDG30DC is Yanmar's most popular commercial unit — compact, fuel-efficient, and designed for continuous operation in demanding business environments.",
    features: ["Compact footprint for tight plant rooms", "8-hour base tank at 75% load", "Auto-start on mains failure", "Anti-vibration rubber mounts"],
    inStock: true,
    badge: "Best Seller",
    image: "https://tse3.mm.bing.net/th/id/OIP.B3D_TCKh_3HnN6GenBfc3QHaE5?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Yanmar 30kW commercial diesel generator"
  },
  {
    id: "yanmar-40kw-comm-023",
    name: "Yanmar YDG40DC Commercial",
    brand: "Yanmar",
    category: "commercial",
    kw: 40,
    fuel: "Diesel",
    price: 3000,
    originalPrice: 3500,
    description: "40kW of dependable diesel power for restaurants, medical offices, and mid-size commercial buildings. Low maintenance, high uptime.",
    features: ["Deep-sea DSE controller", "Remote monitoring via Ethernet", "Dual-skin acoustic canopy option", "12-month / 1,000-hour service intervals"],
    inStock: true,
    badge: null,
    image: "https://static.wixstatic.com/media/49c4f5_24e444637dba4a20b2a287e8ca38e8fb~mv2.png/v1/fill/w_600,h_600,al_c,q_85,enc_avif,quality_auto/49c4f5_24e444637dba4a20b2a287e8ca38e8fb~mv2.png",
    imageSearch: "Yanmar 40kW commercial diesel generator"
  },
  {
    id: "yanmar-50kw-comm-024",
    name: "Yanmar YDG50DC Commercial",
    brand: "Yanmar",
    category: "commercial",
    kw: 50,
    fuel: "Diesel",
    price: 3200,
    originalPrice: 3700,
    description: "The YDG50DC keeps your business running during grid failures with 50kW of reliable diesel output and industry-leading fuel economy.",
    features: ["50kW at 0.8 power factor", "Heavy-duty alternator — IP23 rated", "Business continuity auto-restart", "2-year comprehensive warranty"],
    inStock: true,
    badge: null,
    image: "https://tse2.mm.bing.net/th/id/OIP.mSDZdDiyYnN2_ttz5An7OAHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Yanmar 50kW commercial diesel generator"
  },
  {
    id: "yanmar-60kw-comm-025",
    name: "Yanmar YDG60DC Commercial",
    brand: "Yanmar",
    category: "commercial",
    kw: 60,
    fuel: "Diesel",
    price: 3500,
    originalPrice: 4000,
    description: "60kW commercial diesel generator with advanced DSE controller, built for large retail outlets, warehouses, and multi-tenant buildings.",
    features: ["DSE7320 MKII controller", "Paralleling capability for N+1 redundancy", "Automatic load sharing", "IP54 weatherproof main switchgear"],
    inStock: true,
    badge: null,
    image: "https://tse2.mm.bing.net/th/id/OIP.K0UEcarYZaGgReue98GPRQHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Yanmar 60kW commercial diesel generator"
  },
  {
    id: "yanmar-75kw-comm-026",
    name: "Yanmar YDG75DC Commercial",
    brand: "Yanmar",
    category: "commercial",
    kw: 75,
    fuel: "Diesel",
    price: 3800,
    originalPrice: 4400,
    description: "75kW of robust Yanmar diesel power for large commercial facilities. Tier-4 Final emissions, low-maintenance design, and 2-year warranty.",
    features: ["Tier-4 Final ultra-low emissions", "Low-idle fuel-save mode", "Tamper-proof lockable canopy", "Cloud-based fleet management portal"],
    inStock: true,
    badge: null,
    image: "https://www.yanmar.com/global/powerproducts/products/diesel_generators/img/img_index_14.jpg",
    imageSearch: "Yanmar 75kW commercial diesel generator"
  },

  {
    id: "johndeere-20kw-comm-027",
    name: "John Deere 20kW Diesel Commercial",
    brand: "John Deere",
    category: "commercial",
    kw: 20,
    fuel: "Diesel",
    price: 2600,
    originalPrice: 3050,
    description: "John Deere's commercial diesel entry-level — same PowerTech engine found in their construction equipment, delivering unmatched dependability.",
    features: ["John Deere PowerTech diesel engine", "Heavy-duty steel baseframe", "Automatic voltage regulation", "Global John Deere dealer support"],
    inStock: true,
    badge: null,
    image: "https://cdn11.bigcommerce.com/s-7y2ct/images/stencil/1280x1280/products/2137/47126/20-kw-generator__63812.1625312721.jpg?c=2",
    imageSearch: "John Deere 20kW commercial diesel generator"
  },
  {
    id: "johndeere-35kw-comm-028",
    name: "John Deere 35kW Diesel Commercial",
    brand: "John Deere",
    category: "commercial",
    kw: 35,
    fuel: "Diesel",
    price: 2900,
    originalPrice: 3400,
    description: "35kW John Deere commercial generator — trusted by construction companies, municipalities, and school districts nationwide.",
    features: ["Anti-freeze coolant heater", "Extended 500-hour oil change", "AmpSentry protection relay", "Standard with oil separator"],
    inStock: true,
    badge: null,
    image: "https://tse2.mm.bing.net/th/id/OIP.8i2X8S2R0dKc5r-AKS_BgQHaFj?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "John Deere 35kW commercial generator"
  },
  {
    id: "johndeere-50kw-comm-029",
    name: "John Deere 50kW Diesel Commercial",
    brand: "John Deere",
    category: "commercial",
    kw: 50,
    fuel: "Diesel",
    price: 3200,
    originalPrice: 3700,
    description: "The John Deere 50kW commercial diesel generator is built for mission-critical business use with a robust alternator and digital monitoring suite.",
    features: ["InPower Pro diagnostic software", "Isolated sub-base fuel tank option", "Digital governor for ±0.25% regulation", "UL 2200 listed"],
    inStock: true,
    badge: "New",
    image: "https://americasgenerators.com/wp-content/uploads/2020/04/Product-Feature-50-kW-John-Deere-Diesel-Generator-%E2%80%93-EPA-Tier-4.png",
    imageSearch: "John Deere 50kW diesel generator"
  },
  {
    id: "johndeere-75kw-comm-030",
    name: "John Deere 75kW Diesel Commercial",
    brand: "John Deere",
    category: "commercial",
    kw: 75,
    fuel: "Diesel",
    price: 3700,
    originalPrice: 4200,
    description: "John Deere's high-capacity 75kW commercial diesel — preferred by hospitals, data centres, and government facilities for their proven reliability record.",
    features: ["Hospital-grade EMI suppression", "Critical power relay protection", "3-phase 480V / 208V output options", "Full load test documentation included"],
    inStock: true,
    badge: null,
    image: "https://tse2.mm.bing.net/th/id/OIP.XE-hsWa9hz_Gvmjgqe66iQHaFj?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "John Deere 75kW commercial diesel generator"
  },

  {
    id: "cummins-22kw-comm-031",
    name: "Cummins C22D5 22kW Commercial",
    brand: "Cummins",
    category: "commercial",
    kw: 22,
    fuel: "Diesel",
    price: 2700,
    originalPrice: 3150,
    description: "Cummins commercial-grade 22kW diesel with PowerCommand controller — the preferred generator brand of Fortune 500 facilities managers globally.",
    features: ["PowerCommand 1.1 digital controller", "24V DC electric start system", "Ripple-free DC charging alternator", "500-hour extended service interval"],
    inStock: true,
    badge: null,
    image: "https://th.bing.com/th/id/R.395a592b79e4934e9be0d9cf3d8a6fc0?rik=74yeGlxHiB0DUw&pid=ImgRaw&r=0",
    imageSearch: "Cummins C22D5 commercial diesel generator"
  },
  {
    id: "cummins-33kw-comm-032",
    name: "Cummins C33D5 33kW Commercial",
    brand: "Cummins",
    category: "commercial",
    kw: 33,
    fuel: "Diesel",
    price: 3000,
    originalPrice: 3500,
    description: "33kW commercial standby with Cummins' advanced load management and paralleling capability. Ideal for growing businesses requiring scalable power.",
    features: ["Parallel-ready bus terminals", "NFPA 110 Level 1 compliant", "Integrated surge arrester", "PowerCommand 2.2 controller"],
    inStock: true,
    badge: "Best Seller",
    image: "https://tse2.mm.bing.net/th/id/OIP.6iCJ2Qs_0KaWVdO9_fLfqwHaHa?rs=1&pid=ImgDetMain&o=7&rm=3l",
    imageSearch: "Cummins C33D5 commercial generator"
  },
  {
    id: "cummins-55kw-comm-033",
    name: "Cummins C55D5 55kW Commercial",
    brand: "Cummins",
    category: "commercial",
    kw: 55,
    fuel: "Diesel",
    price: 3400,
    originalPrice: 3900,
    description: "55kW of Cummins commercial diesel power with full 3-phase output and market-leading warranty. Powers entire commercial buildings during outages.",
    features: ["3-phase 480V output standard", "Low idle cool-down cycle", "Fault memory with 64-event log", "2-year / 1,000-hour warranty"],
    inStock: true,
    badge: null,
    image: "https://tse1.mm.bing.net/th/id/OIP.h4cuxaD4M3Xb7LyYhldf3gHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Cummins 55kW commercial diesel generator"
  },
  {
    id: "cummins-80kw-comm-034",
    name: "Cummins C80D5 80kW Commercial",
    brand: "Cummins",
    category: "commercial",
    kw: 80,
    fuel: "Diesel",
    price: 3900,
    originalPrice: 4400,
    description: "The C80D5 delivers 80kW of prime or standby power for large commercial applications. Supports paralleling to scale to any load requirement.",
    features: ["Scalable via paralleling up to 32 units", "Integrated PowerCommand ATS interface", "Marine-grade alternator windings", "Zero-power loss transfer option"],
    inStock: true,
    badge: null,
    image: "https://tse3.mm.bing.net/th/id/OIP.LG_8QKqHho4ui8UEOue8_QHaFD?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Cummins C80D5 80kW commercial generator"
  },

  {
    id: "caterpillar-22kw-comm-035",
    name: "Caterpillar DE22GC 22kW Commercial",
    brand: "Caterpillar",
    category: "commercial",
    kw: 22,
    fuel: "Diesel",
    price: 2800,
    originalPrice: 3300,
    description: "Caterpillar's compact 22kW diesel generator — Cat quality in a compact package for small commercial premises, telecom shelters, and light industry.",
    features: ["Cat C1.5 diesel engine", "Compact generator 'Gas Cap' design", "EMCP 4.1 digital controller", "Extended service kits available"],
    inStock: true,
    badge: null,
    image: "https://th.bing.com/th/id/R.8d11d9f705d89d051d8a1aab1d511aad?rik=sz%2f4ma5DoCrDSA&pid=ImgRaw&r=0",
    imageSearch: "Caterpillar 22kW commercial diesel generator"
  },
  {
    id: "caterpillar-33kw-comm-036",
    name: "Caterpillar DE33GC 33kW Commercial",
    brand: "Caterpillar",
    category: "commercial",
    kw: 33,
    fuel: "Diesel",
    price: 3100,
    originalPrice: 3600,
    description: "The Cat DE33GC combines market-leading fuel efficiency with the reliability of Cat's global support network. Trusted by business continuity professionals.",
    features: ["EMCP 4.2 controller with data logging", "Anti-condensation heater standard", "Modular acoustic enclosure", "24-hour base fuel tank"],
    inStock: true,
    badge: "New",
    image: "https://tse4.mm.bing.net/th/id/OIP.y7q4FmK2aX-fZpw02c4zlwHaFj?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Caterpillar DE33GC commercial generator"
  },
  {
    id: "caterpillar-55kw-comm-037",
    name: "Caterpillar DE55GC 55kW Commercial",
    brand: "Caterpillar",
    category: "commercial",
    kw: 55,
    fuel: "Diesel",
    price: 3600,
    originalPrice: 4100,
    description: "Cat's 55kW commercial diesel — engineered for 25,000+ hours of reliable service with minimal maintenance and global Cat dealer support in 180 countries.",
    features: ["25,000-hour design life", "Cat EMCP 4.4 touchscreen controller", "Integrated anti-theft immobiliser", "Smart load management system"],
    inStock: true,
    badge: null,
    image: "https://tse1.mm.bing.net/th/id/OIP.6NdRIJXIAEVUSJZeOhQ0YwHaFj?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Caterpillar DE55GC 55kW commercial generator"
  },

  {
    id: "perkins-20kw-comm-038",
    name: "Perkins 20kW Diesel Commercial",
    brand: "Perkins",
    category: "commercial",
    kw: 20,
    fuel: "Diesel",
    price: 2550,
    originalPrice: 2999,
    description: "Perkins-powered 20kW commercial diesel — the engine brand specified by over 1,000 OEMs worldwide. Reliable, compact, and easy to service.",
    features: ["Perkins 1100 Series engine", "Mechanical governor option", "Tropical rating available", "Global spare parts availability"],
    inStock: true,
    badge: null,
    image: "https://tse2.mm.bing.net/th/id/OIP.mDKFb0xvcLIu7cwGzqP-eQAAAA?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Perkins 20kW commercial diesel generator"
  },
  {
    id: "perkins-45kw-comm-039",
    name: "Perkins 45kW Diesel Commercial",
    brand: "Perkins",
    category: "commercial",
    kw: 45,
    fuel: "Diesel",
    price: 3100,
    originalPrice: 3600,
    description: "A proven performer at 45kW, the Perkins commercial diesel delivers outstanding transient response and minimal fuel burn for 24/7 standby use.",
    features: ["Perkins 1204 Series engine", "Electronic governor ±0.5% regulation", "Compact baseframe — ships in container", "Anti-vibration mount system"],
    inStock: true,
    badge: null,
    image: "https://tse1.mm.bing.net/th/id/OIP.7wyUrF19smt4fte5Rpy0rAHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Perkins 45kW commercial diesel generator"
  },

  {
    id: "kohler-80kw-comm-040",
    name: "Kohler 80REOZJF 80kW Commercial",
    brand: "Kohler",
    category: "commercial",
    kw: 80,
    fuel: "Diesel",
    price: 3900,
    originalPrice: 4450,
    description: "Kohler's 80kW commercial diesel generator — industrial-grade reliability with premium acoustic enclosure, digital controls, and Kohler's 5-year warranty.",
    features: ["5-year / 2,000-hour Kohler warranty", "Premium acoustic-lined enclosure", "Automatic weekly exercise cycle", "3-phase output 120/208V or 277/480V"],
    inStock: true,
    badge: null,
    image: "https://tse2.mm.bing.net/th/id/OIP.U2gph_EBmnYwuYlvWRZO5gHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Kohler 80kW commercial diesel generator"
  },


  // ─────────────────────────────────────────────────────────────
  // INDUSTRIAL DIESEL  (20 products · 100–500 kW · $4,000–$7,000)
  // ─────────────────────────────────────────────────────────────

  {
    id: "yanmar-100kw-ind-041",
    name: "Yanmar YDG100IND Industrial",
    brand: "Yanmar",
    category: "industrial",
    kw: 100,
    fuel: "Diesel",
    price: 4200,
    originalPrice: 4900,
    description: "Yanmar's entry into industrial diesel generation — 100kW of Tier-4 Final compliant power for manufacturing plants, cold storage, and process industries.",
    features: ["Tier-4 Final SCR exhaust treatment", "IP54 weatherproof control panel", "Synchronising-ready controller", "Critical power relay system"],
    inStock: true,
    badge: null,
    image: "https://tse1.mm.bing.net/th/id/OIP.AFMxHoCjOoA7tVSbXeMk0QHaFj?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Yanmar 100kW industrial diesel generator"
  },
  {
    id: "yanmar-125kw-ind-042",
    name: "Yanmar YDG125IND Industrial",
    brand: "Yanmar",
    category: "industrial",
    kw: 125,
    fuel: "Diesel",
    price: 4600,
    originalPrice: 5300,
    description: "125kW industrial diesel with advanced AVR and paralleling bus — designed for N+1 redundant power systems in critical infrastructure facilities.",
    features: ["N+1 paralleling ready", "Digital AVR ±1% voltage regulation", "1,500-hour oil change interval", "NFPA 110 Level 1 compliant"],
    inStock: true,
    badge: "Best Seller",
    image: "https://www.yanmar.com/global/powerproducts/products/diesel_generators/img/img_index_14.jpg",
    imageSearch: "Yanmar 125kW industrial diesel generator"
  },
  {
    id: "yanmar-150kw-ind-043",
    name: "Yanmar YDG150IND Industrial",
    brand: "Yanmar",
    category: "industrial",
    kw: 150,
    fuel: "Diesel",
    price: 4900,
    originalPrice: 5700,
    description: "The YDG150IND is engineered for mission-critical applications in data centres, hospitals, and government facilities where zero-downtime is non-negotiable.",
    features: ["Mission-critical reliability rating", "Integrated emergency stop loop", "Dual redundant starting batteries", "IBC seismic code certified"],
    inStock: true,
    badge: null,
    image: "https://tse1.mm.bing.net/th/id/OIP.m42JzCGypCztHN58_wno2wHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Yanmar 150kW industrial diesel generator"
  },
  {
    id: "yanmar-200kw-ind-044",
    name: "Yanmar YDG200IND Industrial",
    brand: "Yanmar",
    category: "industrial",
    kw: 200,
    fuel: "Diesel",
    price: 5500,
    originalPrice: 6300,
    description: "200kW industrial standby generator with Tier-4 Final compliance and advanced digital controls. Suitable for large manufacturing and processing plants.",
    features: ["Tier-4 Final DOC + DPF system", "480V 3-phase standard output", "Remote telemetry module included", "Heavy-duty skid with forklift pockets"],
    inStock: true,
    badge: null,
    image: "https://4.imimg.com/data4/FQ/LA/MY-12492589/perkins-silent-diesel-generator-500x500.jpg",
    imageSearch: "Yanmar 200kW industrial generator"
  },
  {
    id: "yanmar-250kw-ind-045",
    name: "Yanmar YDG250IND Industrial",
    brand: "Yanmar",
    category: "industrial",
    kw: 250,
    fuel: "Diesel",
    price: 6200,
    originalPrice: 7100,
    description: "250kW of high-performance Yanmar industrial diesel power. Paralleling capability enables scalable power systems up to megawatt scale.",
    features: ["Megawatt-scale paralleling bus", "isochronous load sharing", "Remote cloud-based diagnostics", "Stainless steel exhaust system"],
    inStock: false,
    badge: null,
    image: "https://image.made-in-china.com/43f34j00yceuqlohkIkN/250kw-Container-Type-Diesel-Generator-Powered-by-Industrial-6-Cylinder-Generator.webp",
    imageSearch: "Yanmar 250kW industrial diesel generator"
  },

  {
    id: "johndeere-100kw-ind-046",
    name: "John Deere 100kW Industrial Diesel",
    brand: "John Deere",
    category: "industrial",
    kw: 100,
    fuel: "Diesel",
    price: 4300,
    originalPrice: 5000,
    description: "John Deere industrial-grade 100kW diesel generator. The PowerTech industrial engine is rated for continuous duty in the harshest environments.",
    features: ["PowerTech industrial diesel — continuous rated", "InPower Pro remote diagnostics", "Skid-mounted with integral fuel tank", "UL 2200 listed"],
    inStock: true,
    badge: null,
    image: "https://static.wixstatic.com/media/a10320_f358282683eb4105a75f655fe44180be~mv2.png/v1/fill/w_1182,h_827,al_c,q_90,usm_0.66_1.00_0.01,enc_avif,quality_auto/a10320_f358282683eb4105a75f655fe44180be~mv2.png",
    imageSearch: "John Deere 100kW industrial diesel generator"
  },
  {
    id: "johndeere-150kw-ind-047",
    name: "John Deere 150kW Industrial Diesel",
    brand: "John Deere",
    category: "industrial",
    kw: 150,
    fuel: "Diesel",
    price: 5000,
    originalPrice: 5800,
    description: "150kW John Deere industrial diesel — trusted in mining, oil & gas, and large commercial construction sites worldwide.",
    features: ["Rated for altitude to 6,000 ft", "Oil heater for cold-start reliability", "Integrated fuel day tank", "Load bank testing pre-delivery"],
    inStock: true,
    badge: null,
    image: "https://static.wixstatic.com/media/a10320_d5b3ec2d90754600ad96ef805f5e7def~mv2.png/v1/fill/w_859,h_827,al_c,q_90,usm_0.66_1.00_0.01,enc_avif,quality_auto/a10320_d5b3ec2d90754600ad96ef805f5e7def~mv2.png",
    imageSearch: "John Deere 150kW industrial generator"
  },
  {
    id: "johndeere-200kw-ind-048",
    name: "John Deere 200kW Industrial Diesel",
    brand: "John Deere",
    category: "industrial",
    kw: 200,
    fuel: "Diesel",
    price: 5700,
    originalPrice: 6500,
    description: "John Deere 200kW industrial — a preferred choice for water treatment plants, airports, and large manufacturing facilities requiring continuous duty diesel power.",
    features: ["Continuous duty rated at 200kW", "SCADA integration ready", "IP65 control panel", "Full factory load test certificate"],
    inStock: true,
    badge: null,
    image: "https://static.wixstatic.com/media/a10320_6a6be591777348eba420bffe90de1bcd~mv2.png/v1/fill/w_859,h_827,al_c,q_90,usm_0.66_1.00_0.01,enc_avif,quality_auto/a10320_6a6be591777348eba420bffe90de1bcd~mv2.png",
    imageSearch: "John Deere 200kW industrial diesel generator"
  },
  {
    id: "johndeere-300kw-ind-049",
    name: "John Deere 300kW Industrial Diesel",
    brand: "John Deere",
    category: "industrial",
    kw: 300,
    fuel: "Diesel",
    price: 6500,
    originalPrice: 7400,
    description: "John Deere's 300kW industrial diesel is built for data centres, healthcare facilities, and mission-critical infrastructure where power failure is not an option.",
    features: ["Data centre power quality compliance", "Integrated paralleling switchgear", "Healthcare-grade transient response", "2,000-hour service interval"],
    inStock: true,
    badge: "New",
    image: "https://static.wixstatic.com/media/a10320_c161735fee224c788ef8505ff6b8abca~mv2.jpeg/v1/fill/w_1055,h_827,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/a10320_c161735fee224c788ef8505ff6b8abca~mv2.jpeg",
    imageSearch: "John Deere 300kW industrial diesel generator"
  },

  {
    id: "cummins-100kw-ind-050",
    name: "Cummins C100D6 100kW Industrial",
    brand: "Cummins",
    category: "industrial",
    kw: 100,
    fuel: "Diesel",
    price: 4400,
    originalPrice: 5100,
    description: "The Cummins C100D6 is the world's most deployed 100kW industrial diesel generator. Trusted in over 190 countries with a comprehensive global service network.",
    features: ["PowerCommand 3.3 PLC controller", "Deployed in 190+ countries", "HMI touchscreen display", "Anti-condensation winding heaters"],
    inStock: true,
    badge: "Best Seller",
    image: "https://shop.seypromi.com/cdn/shop/files/Generador_Cummins_100kw_C100D6_vista_2.jpg?v=1762406128&width=1024",
    imageSearch: "Cummins C100D6 100kW industrial generator"
  },
  {
    id: "cummins-150kw-ind-051",
    name: "Cummins C150D6 150kW Industrial",
    brand: "Cummins",
    category: "industrial",
    kw: 150,
    fuel: "Diesel",
    price: 5100,
    originalPrice: 5900,
    description: "150kW of Cummins industrial diesel power with NFPA 110 compliance, Tier-4 Final emissions, and isochronous load sharing for parallel systems.",
    features: ["NFPA 110 Level 1 emergency certified", "Tier-4 Final diesel DOC system", "Isochronous load sharing controller", "On-board monitoring with fault history"],
    inStock: true,
    badge: null,
    image: "https://th.bing.com/th/id/R.447bd78826392b915b23b2b4b05429f5?rik=KPvg5djrunT%2bdA&pid=ImgRaw&r=0",
    imageSearch: "Cummins 150kW industrial diesel generator"
  },
  {
    id: "cummins-200kw-ind-052",
    name: "Cummins C200D6 200kW Industrial",
    brand: "Cummins",
    category: "industrial",
    kw: 200,
    fuel: "Diesel",
    price: 5800,
    originalPrice: 6700,
    description: "The C200D6 is Cummins' most specified 200kW industrial unit, used in hospitals, airports, and large data centres across North America.",
    features: ["Hospital-grade power quality", "Airport infrastructure certified", "Fuel-efficient QSL9 engine", "Integrated AMF panel with 4-pole ATS"],
    inStock: true,
    badge: null,
    image: "https://tse2.mm.bing.net/th/id/OIP.Z0MB4tKDVkgiB7oMi2C5RQHaEK?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Cummins C200D6 200kW industrial generator"
  },
  {
    id: "cummins-300kw-ind-053",
    name: "Cummins C300D6 300kW Industrial",
    brand: "Cummins",
    category: "industrial",
    kw: 300,
    fuel: "Diesel",
    price: 6700,
    originalPrice: 7600,
    description: "300kW Cummins industrial diesel for large commercial buildings, manufacturing facilities, and critical infrastructure. Designed for 30+ years of service.",
    features: ["30-year design life rating", "Modular switchgear integration", "Predictive maintenance analytics", "Full IEC 60034 alternator compliance"],
    inStock: false,
    badge: null,
    image: "https://tse4.mm.bing.net/th/id/OIP.vqDDezHQus_Db8pSgLvIkwHaFS?w=560&h=400&rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Cummins 300kW industrial diesel generator"
  },

  {
    id: "caterpillar-110kw-ind-054",
    name: "Caterpillar DE110GC 110kW Industrial",
    brand: "Caterpillar",
    category: "industrial",
    kw: 110,
    fuel: "Diesel",
    price: 4500,
    originalPrice: 5200,
    description: "The Cat DE110GC combines Cat's legendary build quality with advanced EMCP controller technology for seamless integration into complex power systems.",
    features: ["EMCP 4.4 touchscreen controller", "Integrated surge protection", "25,000-hour design life", "Global Cat dealer network support"],
    inStock: true,
    badge: null,
    image: "https://tse1.mm.bing.net/th/id/OIP.CIsCUIpD30YxBVHzZQ_QlwHaEb?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Caterpillar DE110GC 110kW industrial generator"
  },
  {
    id: "caterpillar-165kw-ind-055",
    name: "Caterpillar DE165GC 165kW Industrial",
    brand: "Caterpillar",
    category: "industrial",
    kw: 165,
    fuel: "Diesel",
    price: 5200,
    originalPrice: 6000,
    description: "165kW of Cat industrial power — specified for critical facilities, mining operations, and oil & gas platforms requiring extreme reliability.",
    features: ["Oil and gas platform certified", "Marine duty rating available", "Dual-bearing alternator", "Heavy-duty steel baseframe"],
    inStock: true,
    badge: "New",
    image: "https://tse2.mm.bing.net/th/id/OIP.qN_29Td0Gc9zkM1S_1IHgQHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Caterpillar DE165GC industrial diesel generator"
  },
  {
    id: "caterpillar-330kw-ind-056",
    name: "Caterpillar DE330GC 330kW Industrial",
    brand: "Caterpillar",
    category: "industrial",
    kw: 330,
    fuel: "Diesel",
    price: 6800,
    originalPrice: 7700,
    description: "The Cat DE330GC is one of the most powerful units in Cat's commercial range, delivering 330kW of prime power for large industrial plants.",
    features: ["330kW continuous prime power", "Tier-4 Final DPF exhaust treatment", "EMCP 4.4 with paralleling PLC", "Seismic zone 4 certified"],
    inStock: false,
    badge: null,
    image: "https://tse1.mm.bing.net/th/id/OIP.7ni-lfFgNk_52Rk-PiXlbAHaFj?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Caterpillar DE330GC 330kW industrial generator"
  },

  {
    id: "perkins-100kw-ind-057",
    name: "Perkins 100kW Industrial Diesel",
    brand: "Perkins",
    category: "industrial",
    kw: 100,
    fuel: "Diesel",
    price: 4200,
    originalPrice: 4900,
    description: "Perkins 1206 Series-powered 100kW industrial generator. Perkins engines are fitted in more generator sets globally than any other brand.",
    features: ["Perkins 1206 Series engine", "Electronic governor — ±0.5% regulation", "Tropical rating for hot climates", "Worldwide spare parts within 24 hours"],
    inStock: true,
    badge: null,
    image: "https://tse1.mm.bing.net/th/id/OIP.Xfo5wlJ5p2gWf0N19lermQHaFj?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Perkins 100kW industrial diesel generator"
  },
  {
    id: "perkins-200kw-ind-058",
    name: "Perkins 200kW Industrial Diesel",
    brand: "Perkins",
    category: "industrial",
    kw: 200,
    fuel: "Diesel",
    price: 5600,
    originalPrice: 6400,
    description: "200kW Perkins-powered industrial generator — high transient performance and proven reliability for manufacturing plants, pumping stations, and utilities.",
    features: ["Perkins 2206 Series engine", "High transient load acceptance", "DSE 7320 MKII digital controller", "Anti-vibration isolation mounts"],
    inStock: true,
    badge: "New",
    image: "https://tse2.mm.bing.net/th/id/OIP.fZA8gbyTQ5BRN2MFVewHEAHaFZ?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Perkins 200kW industrial diesel generator"
  },

  {
    id: "mtu-165kw-ind-059",
    name: "MTU 12V1600 DS165 165kW Industrial",
    brand: "MTU",
    category: "industrial",
    kw: 165,
    fuel: "Diesel",
    price: 5400,
    originalPrice: 6200,
    description: "MTU's 165kW industrial diesel — the choice of premium data centres and tier-1 hospitals demanding the highest possible power quality and uptime.",
    features: ["MTU Series 1600 high-performance engine", "Tier-4 Final with SCR system", "99.999% reliability target design", "Integrated SCADA-ready controller"],
    inStock: true,
    badge: "New",
    image: "https://tse2.mm.bing.net/th/id/OIP.axf-GywoXkofoXYfPdnIDwHaE9?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "MTU 165kW industrial diesel generator"
  },
  {
    id: "mtu-500kw-ind-060",
    name: "MTU 16V2000 DS500 500kW Industrial",
    brand: "MTU",
    category: "industrial",
    kw: 500,
    fuel: "Diesel",
    price: 7000,
    originalPrice: 7900,
    description: "MTU's flagship 500kW — the pinnacle of industrial diesel generator technology. Specified by the world's most demanding data centres, defence facilities, and utilities.",
    features: ["500kW continuous prime power", "MTU Series 2000 V16 engine", "Integrated PowerCommand paralleling", "IEC 60034 Class H insulation"],
    inStock: false,
    badge: null,
    image: "https://5.imimg.com/data5/SELLER/Default/2023/2/CZ/MG/SL/656503/force-mtu-diesel-generator-500x500.png",
    imageSearch: "MTU 500kW industrial diesel generator 16V2000"
  },


  // ─────────────────────────────────────────────────────────────
  // PORTABLE  (12 products · 3–12 kW · $400–$1,200)
  // ─────────────────────────────────────────────────────────────

  {
    id: "honda-3kw-port-061",
    name: "Honda EU3000iS Portable Inverter",
    brand: "Honda",
    category: "portable",
    kw: 3,
    fuel: "Gasoline",
    price: 1049,
    originalPrice: 1199,
    description: "Honda's most popular portable inverter generator — ultra-quiet, fuel efficient, and powerful enough for RV, tailgating, and home backup.",
    features: ["Eco-throttle for up to 20 hrs runtime", "Ultra-quiet 57–65 dB operation", "Electric start with backup recoil", "Parallel-capable for double power"],
    inStock: true,
    badge: "Best Seller",
    image: "https://tse3.mm.bing.net/th/id/OIP.hHrQ3mjtHD1OheHSXUrmQQHaE3?w=1024&h=674&rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Honda EU3000iS portable generator"
  },
  {
    id: "honda-5kw-port-062",
    name: "Honda EB5000X Portable Generator",
    brand: "Honda",
    category: "portable",
    kw: 5,
    fuel: "Gasoline",
    price: 1149,
    originalPrice: 1299,
    description: "Honda's workhorse 5kW portable — built for construction sites and outdoor events. GX commercial-grade engine for extended daily use.",
    features: ["GX commercial-grade engine", "GFCI protected duplex outlets", "Hour meter and oil alert", "Fold-down handle for storage"],
    inStock: true,
    badge: null,
    image: "https://tse3.mm.bing.net/th/id/OIP.-zKjqfCr1rljGWuo6tMB6gHaE7?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Honda EB5000X portable generator"
  },
  {
    id: "honda-65kw-port-063",
    name: "Honda EM6500SX Portable Generator",
    brand: "Honda",
    category: "portable",
    kw: 6.5,
    fuel: "Gasoline",
    price: 1199,
    originalPrice: 1349,
    description: "6,500 watts of Honda reliability with electric start, large fuel tank, and iAVR technology for stable power to sensitive electronics.",
    features: ["iAVR technology — clean stable power", "8.1-gallon tank for 17 hrs runtime", "Electric start with remote panel option", "Fully CARB compliant"],
    inStock: true,
    badge: null,
    image: "https://tse2.mm.bing.net/th/id/OIP.kwW-Sq5sw4eTLWM5WkU_IgHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Honda EM6500SX portable generator"
  },

  {
    id: "champion-35kw-port-064",
    name: "Champion 3500W Portable Generator",
    brand: "Champion",
    category: "portable",
    kw: 3.5,
    fuel: "Gasoline",
    price: 449,
    originalPrice: 529,
    description: "Champion's most popular portable — 3,500 running watts with a 4-gallon tank and 12 hours of runtime. Perfect for emergency home backup.",
    features: ["3,500W running / 4,000W peak", "12 hrs at 50% load", "Cold-start technology", "Covered outlets with volt guard"],
    inStock: true,
    badge: "Best Seller",
    image: "https://tse2.mm.bing.net/th/id/OIP.b3_vnjjRQwjhlKXt4hXuHQHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Champion 3500W portable generator"
  },
  {
    id: "champion-75kw-port-065",
    name: "Champion 7500W Electric Start Portable",
    brand: "Champion",
    category: "portable",
    kw: 7.5,
    fuel: "Gasoline",
    price: 749,
    originalPrice: 899,
    description: "Champion's 7,500W electric start portable — ideal for job sites and home backup. Powers central air, appliances, and tools simultaneously.",
    features: ["7,500W running / 9,375W peak", "Electric start with recoil backup", "30A RV outlet included", "Never-flat wheels for easy transport"],
    inStock: true,
    badge: null,
    image: "https://th.bing.com/th/id/R.ed08157b347ca8039a9f0870c4a4e85c?rik=G8XUCicCCWixkg&pid=ImgRaw&r=0",
    imageSearch: "Champion 7500W electric start portable generator"
  },
  {
    id: "champion-12kw-port-066",
    name: "Champion 12,000W Portable Generator",
    brand: "Champion",
    category: "portable",
    kw: 12,
    fuel: "Gasoline",
    price: 1099,
    originalPrice: 1299,
    description: "Champion's highest output portable — 12,000 peak watts with remote key fob start. Powers your entire home during extended outages.",
    features: ["Remote key fob start up to 80 ft", "12,000W peak / 9,500W running", "Low-oil shut-off protection", "Intelligauge voltage and Hz meter"],
    inStock: true,
    badge: null,
    image: "https://tse4.mm.bing.net/th/id/OIP.8ccKPCSmd_LgLHjCPq_lIAHaE8?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Champion 12000W portable generator"
  },

  {
    id: "westinghouse-36kw-port-067",
    name: "Westinghouse WGen3600 Portable",
    brand: "Westinghouse",
    category: "portable",
    kw: 3.6,
    fuel: "Gasoline",
    price: 449,
    originalPrice: 529,
    description: "Westinghouse WGen3600 — lightweight and powerful with a 4-gallon tank and easy recoil start. Great for camping, tailgating, and emergency use.",
    features: ["3,600W running / 4,650W peak", "4-gallon tank — 18 hrs runtime", "Integrated fuel gauge", "Telescoping handle and flat-free wheels"],
    inStock: true,
    badge: null,
    image: "https://tse1.mm.bing.net/th/id/OIP.zDgeAUeujuUr1cOkd7QxLQHaGc?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Westinghouse WGen3600 portable generator"
  },
  {
    id: "westinghouse-75kw-port-068",
    name: "Westinghouse WGen7500 Portable",
    brand: "Westinghouse",
    category: "portable",
    kw: 7.5,
    fuel: "Gasoline",
    price: 729,
    originalPrice: 879,
    description: "The WGen7500 is a top-rated portable generator with remote electric start, data centre on the panel, and a large 6.6-gallon fuel tank.",
    features: ["Remote electric start included", "6.6-gallon tank — 16 hrs runtime", "Digital data centre display", "Automatic low-oil shutdown"],
    inStock: true,
    badge: "Best Seller",
    image: "https://th.bing.com/th/id/R.040ec47da3c04e8e2365a14610cac674?rik=ybZfDzSseNjr8A&pid=ImgRaw&r=0",
    imageSearch: "Westinghouse WGen7500 portable generator"
  },
  {
    id: "westinghouse-12kw-port-069",
    name: "Westinghouse WGen12000 Portable",
    brand: "Westinghouse",
    category: "portable",
    kw: 12,
    fuel: "Gasoline",
    price: 1099,
    originalPrice: 1249,
    description: "Westinghouse's flagship portable — 12,000W with a remote key fob, 8-gallon tank, and enough power to run an entire house during an outage.",
    features: ["Remote key fob electric start", "8-gallon tank — 11 hrs runtime", "Transfer switch ready outlet", "Dual USB charging ports"],
    inStock: true,
    badge: null,
    image: "https://tse1.mm.bing.net/th/id/OIP.x8OM1LawZMK43k2RYJ1ekAHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Westinghouse WGen12000 portable generator"
  },

  {
    id: "yamaha-3kw-port-070",
    name: "Yamaha EF3000iSEB Portable Inverter",
    brand: "Yamaha",
    category: "portable",
    kw: 3,
    fuel: "Gasoline",
    price: 1099,
    originalPrice: 1249,
    description: "Yamaha's premium 3kW inverter portable — with electric start, Boost technology, and industry-leading fuel efficiency for extended runtime.",
    features: ["Electric start with boost technology", "EFI fuel system — starts in any temp", "Parallel cable ready", "Extremely quiet 58 dB"],
    inStock: true,
    badge: null,
    image: "https://tse4.mm.bing.net/th/id/OIP.twEA32jQDkGGrzdYNRuJSgHaGI?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Yamaha EF3000iSEB portable generator"
  },
  {
    id: "yamaha-63kw-port-071",
    name: "Yamaha EF6300iSDE Portable Inverter",
    brand: "Yamaha",
    category: "portable",
    kw: 6.3,
    fuel: "Gasoline",
    price: 1149,
    originalPrice: 1299,
    description: "Yamaha's most powerful inverter portable — 6,300W of clean sine-wave power with electric start and ultra-quiet 58 dB operation.",
    features: ["6,300W clean inverter power", "Electric start with auto choke", "Oil watch warning system", "Carrying handles on both sides"],
    inStock: true,
    badge: "Best Seller",
    image: "https://tse4.mm.bing.net/th/id/OIP.gUtkn2mhI3Ikte8rL1e0SwHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Yamaha EF6300iSDE portable generator"
  },

  {
    id: "duromax-12kw-port-072",
    name: "DuroMax XP12000EH Dual Fuel Portable",
    brand: "DuroMax",
    category: "portable",
    kw: 12,
    fuel: "Gasoline",
    price: 999,
    originalPrice: 1199,
    description: "DuroMax's dual-fuel 12,000W portable — runs on gas or propane with electric start and remote key fob. Best value at this wattage class.",
    features: ["Gas or propane dual-fuel operation", "Remote key fob start", "12,000W peak / 9,500W running", "MX2 outlet technology — full 120V/240V"],
    inStock: true,
    badge: null,
    image: "https://tse1.mm.bing.net/th/id/OIP.-D0i_KfB5I3_Clnl9Qq3NgHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "DuroMax XP12000EH dual fuel portable generator"
  },


  // ─────────────────────────────────────────────────────────────
  // INVERTER  (8 products · 1–4 kW · $300–$900)
  // ─────────────────────────────────────────────────────────────

  {
    id: "honda-1kw-inv-073",
    name: "Honda EU1000i Inverter Generator",
    brand: "Honda",
    category: "inverter",
    kw: 1,
    fuel: "Gasoline",
    price: 499,
    originalPrice: 579,
    description: "The world's most popular compact inverter generator. Ultra-lightweight at just 29 lbs — perfect for camping, tailgating, and small electronics.",
    features: ["Only 29 lbs — lightest in class", "Super quiet 53–59 dB", "8.3 hrs runtime at 25% load", "1,000W pure sine-wave output"],
    inStock: true,
    badge: "Best Seller",
    image: "https://static.wixstatic.com/media/5dcc7b_5b60d5d0d41e4a0bba74d33d469e3e70~mv2.png/v1/fill/w_1024,h_682,al_c/EU1000i.png",
    imageSearch: "Honda EU1000i inverter generator"
  },
  {
    id: "honda-22kw-inv-074",
    name: "Honda EU2200i Inverter Generator",
    brand: "Honda",
    category: "inverter",
    kw: 2.2,
    fuel: "Gasoline",
    price: 899,
    originalPrice: 1049,
    description: "Honda's best-selling inverter generator — 2,200W of ultra-clean power in a compact, quiet package. Powers laptops, TVs, and CPAP machines flawlessly.",
    features: ["2,200W clean inverter — THD <3%", "Quietest in its class — 48–57 dB", "Parallel capable — doubles output", "8.1 hrs runtime at 25% load"],
    inStock: true,
    badge: "Best Seller",
    image: "https://th.bing.com/th/id/OIP.nhYwOKQC9VJH7OMi_zUvMQHaFj?w=244&h=183&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3",
    imageSearch: "Honda EU2200i inverter generator"
  },
  {
    id: "honda-32kw-inv-075",
    name: "Honda EU3200i Inverter Generator",
    brand: "Honda",
    category: "inverter",
    kw: 3.2,
    fuel: "Gasoline",
    price: 849,
    originalPrice: 999,
    description: "Honda's newest 3,200W inverter — more power than the EU3000iS in a lighter package, with USB-C PD 60W charging and Bluetooth monitoring.",
    features: ["USB-C Power Delivery 60W charging", "Bluetooth status monitoring", "3,200W — runs most air conditioners", "Auto-throttle eco mode"],
    inStock: true,
    badge: "New",
    image: "https://www.electricgeneratorsdirect.com/products-image/1000/eu3200i_124678_1000_707dbc97ac184f506e662666ae34b0d0.jpg",
    imageSearch: "Honda EU3200i inverter generator"
  },

  {
    id: "yamaha-2kw-inv-076",
    name: "Yamaha EF2000iSv2 Inverter Generator",
    brand: "Yamaha",
    category: "inverter",
    kw: 2,
    fuel: "Gasoline",
    price: 749,
    originalPrice: 879,
    description: "Yamaha's EF2000iSv2 — ultra-reliable 2kW inverter with 10.5 hours of runtime and noise levels starting at just 51.5 dB. A camping and RV favourite.",
    features: ["10.5 hrs runtime at 25% load", "51.5–61 dB ultra-quiet", "Smart throttle for automatic load sensing", "Parallel cable compatible"],
    inStock: true,
    badge: null,
    image: "https://tse2.mm.bing.net/th/id/OIP.N7gCTGsmUhwS-SYxcmyCwgHaE7?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Yamaha EF2000iSv2 inverter generator"
  },
  {
    id: "yamaha-24kw-inv-077",
    name: "Yamaha EF2400iSHC Inverter Generator",
    brand: "Yamaha",
    category: "inverter",
    kw: 2.4,
    fuel: "Gasoline",
    price: 849,
    originalPrice: 999,
    description: "Yamaha's premium 2,400W inverter with an oil-change free design and market-leading 11.5-hour runtime at quarter load — ideal for extended camping trips.",
    features: ["11.5 hrs runtime at 25% load", "Carbon monoxide shut-off (CO sensor)", "Large fuel capacity — 1.6 gallons", "3-year Yamaha warranty"],
    inStock: true,
    badge: "New",
    image: "https://tse2.mm.bing.net/th/id/OIP.0Xq2jNdYMy5c-ZRBfmEk7AHaEK?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Yamaha EF2400iSHC inverter generator"
  },

  {
    id: "westinghouse-12kw-inv-078",
    name: "Westinghouse iGen1200 Inverter",
    brand: "Westinghouse",
    category: "inverter",
    kw: 1.2,
    fuel: "Gasoline",
    price: 349,
    originalPrice: 419,
    description: "Westinghouse's most affordable inverter — 1,200W of clean power for camping, tailgating, and emergency small appliance use. Only 30 lbs.",
    features: ["Only 30 lbs — ultra-portable", "1,200W pure sine-wave inverter", "USB charging port built-in", "CARB and EPA compliant"],
    inStock: true,
    badge: null,
    image: "https://tse3.mm.bing.net/th/id/OIP.HLiRMTCgboaiWPuVDWbYKAHaD4?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Westinghouse iGen1200 inverter generator"
  },
  {
    id: "westinghouse-37kw-inv-079",
    name: "Westinghouse iGen4500 Inverter",
    brand: "Westinghouse",
    category: "inverter",
    kw: 3.7,
    fuel: "Gasoline",
    price: 699,
    originalPrice: 829,
    description: "Westinghouse's flagship consumer inverter — 3,700W of clean power with remote electric start, digital display, and multiple outlet types.",
    features: ["Remote electric start key fob", "4,500W peak / 3,700W running", "TT-30R RV outlet included", "Digital data display — Hz, V, hours"],
    inStock: true,
    badge: "New",
    image: "https://tse1.mm.bing.net/th/id/OIP.hcrrYONcl8WnlTVq0l7AmAHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
    imageSearch: "Westinghouse iGen4500 inverter generator"
  },

  {
    id: "champion-2kw-inv-080",
    name: "Champion 2000W Inverter Generator",
    brand: "Champion",
    category: "inverter",
    kw: 2,
    fuel: "Gasoline",
    price: 449,
    originalPrice: 529,
    description: "Champion's best-value 2,000W inverter — clean power for your electronics, quiet at 53 dB, and only 39 lbs. Great for tailgating and camping.",
    features: ["53 dB ultra-quiet operation", "Only 39 lbs — most portable in class", "Economy mode for longer runtime", "Parallel ready with optional cable"],
    inStock: true,
    badge: null,
    image: "https://www.entreprenadbutiken.com/bilder/artiklar/liten/82001i-DF-SC_S.jpg?m=1621602272",
    imageSearch: "Champion 2000W inverter generator"
  }

];

// For Node.js test only — remove after testing
if (typeof module !== 'undefined') module.exports = PRODUCTS;
